### ISSUE TITLE
Port components to JSS based approach

### ISSUE THREAD

**Issue by bstream** [nordnet/nordnet-ui-kit#121]
To port a component, do this:
* Refactor scss to jss
* Rewrite tests to use new test helpers
* Update styling to new design
* Add component to portedComponent array in `styleguide.config.js`

List of components:
- [x] Icon (#129)
- [x] LabeledValue (#120 - Redefine sizes)
- [x] Badge (#119 - Could need re-styling)
- [x] Avatar ~~TextIcon~~ (#122 - Add more sizes)
- [x] Flag (#126)
- [x] SparkGraph (#133)
- [x] RadioGroup (#134)
- [x] Input (#135) (outstanding: remove BEM, remove bare classes and rework transitions into theme, re-style to new design)
- [x] Dropdown (#137)
- [x] Pane (#138)
- [x] HorizontalNav (#140)
- [x] Tooltip (#139)
- [x] Button (#144)
- [x] Search (#142)
- [x] Table (#145)
- [x] Td (#145)
- [x] Tbody (#145)
- [x] Tfoot (#145)
- [x] Th (#145)
- [x] Thead (#145)
- [x] Tr (#145)
- [x] Logo (#125) (Moved into Icon as `NordnetLogo`) - Candidate for removal
- [x] RatioBar (#134)
- [x] Widget (#146)
- [x] Alert (#130)
- [x] Spinner

Remove these
- ~~Legend (#136, possible candidate for removal)~~
- ~~RangeSelector (#134, Possibly remove this, only used for graphs)~~
- ~~NavBar (#130, Remove this)~~
- ~~GraphTooltip (#128, Remove this)~~
- ~~Select (#134)~~
