### ISSUE TITLE
Styling of all components into new style

### ISSUE THREAD

**Issue by willeeklund** [nordnet/nordnet-ui-kit#151]
List of components:
- [x] Alert (#156)
- [x] Icon (Checking this and adding strokeWidth to an enhancement #174)
- [x] LabeledValue (#155)
- [x] Badge (#157)
- [x] Avatar (#161)
- [x] Flag (Checking this and adding extensions to #180)
- [x] RadioGroup
- [x] Input (#159) (More fixes: #173)
- [x] Dropdown (#153)
- [x] Tooltip (#184)
- [x] Button (#158)
- [x] Spinner (This does not need fixing)
- [x] Table (#163)
- [x] Td (#163)
- [x] Tbody (#163)
- [x] Tfoot (#163)
- [x] Th (#163)
- [x] Thead (#163)
- [x] Tr (#163)
- [x] SegmentedControl (#168)
- ~~SparkGraph (Investigate how to put SparkGraph back, d3-interpolate dependency broke bundle)~~ (#177)
- ~~Search~~ (#179)
- ~~Pane~~ (#175)
- ~~HorizontalNav~~ (#175)
- ~~Widget~~ (#175)
- ~~RatioBar~~ (#175)

**Comment by bstream** [comment]
Wishlist:
* LabeledValue
  * [ ] Redefine sizes for new design
* Icon
  * [ ] Fix for dynamic strokewidth (see svg-icon-template-loader)
* Avatar
  * [ ] Add more sizes, (eg. 56,56,20)
* Theme
  * [ ] Breakpoints
  * [ ] Screen reader only styles
  * [ ] Common styles (headlines etc)
  * [ ] Proper documentation

**Comment by bstream** [comment]
SparkGraph is removed for now because of the many issues with d3, so this issue is done 🎉
